#!/bin/bash
sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mariadb\nDB_HOST=127.0.0.1\nDB_PORT=3306\nDB_DATABASE=laravel\nDB_USERNAME=root\nDB_PASSWORD=/g' .env
sed -i.bak '/# DB_HOST=127.0.0.1/d' .env
sed -i.bak '/# DB_PORT=3306/d' .env
sed -i.bak '/# DB_DATABASE=laravel/d' .env
sed -i.bak '/# DB_USERNAME=root/d' .env
sed -i.bak '/# DB_PASSWORD=/d' .env
